[versions]
agp = "9.1.0"
compileSdk = "36"
documentfile = "1.1.0"
minSdk = "26"
annotation = "1.9.1"
commonsNet = "3.12.0"
gson = "2.13.2"
jimfs = "1.3.1"
kotlin = "2.3.10"
coreKtx = "1.18.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
appcompat = "1.7.1"
kotlinxCoroutinesCore = "1.10.2"
libsuVersion = "5.0.3"
logbackAndroid = "3.0.0"
material = "1.13.0"
constraintlayout = "2.2.1"
mockftpserver = "3.2.0"
mockkVersion = "1.14.9"
navigationFragmentKtx = "2.9.7"
navigationUiKtx = "2.9.7"
okhttp = "5.3.2"
prov = "1.58.0.0"
simplemagic = "1.17"
sshj = "0.40.0"
smbj = "0.14.0"
uiautomator = "2.3.0"
ksp = "2.3.6"
testcontainers = "1.20.1"
commonUiList = "1.0.0-SNAPSHOT"

[libraries]
android-plugin-lib = { module = "com.android.tools.build:gradle", version.ref = "agp" }
androidx-documentfile = { module = "androidx.documentfile:documentfile", version.ref = "documentfile" }
kotlin-plugin-lib = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
androidx-annotation = { module = "androidx.annotation:annotation", version.ref = "annotation" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-uiautomator = { module = "androidx.test.uiautomator:uiautomator", version.ref = "uiautomator" }
common-ktx = { module = "com.storytellerF.common_ui_list:common-ktx", version.ref = "commonUiList" }
common-ui-list-slim-ktx = { module = "com.storytellerF.common_ui_list:slim-ktx", version.ref = "commonUiList" }
compat-ktx = { module = "com.storytellerF.common_ui_list:compat-ktx", version.ref = "commonUiList" }
github-slim-ktx = { module = "com.storytellerF.common_ui_list:slim-ktx" }
slim-ktx = { module = "com.storytellerF.common_ui_list:slim-ktx" }
commons-net = { module = "commons-net:commons-net", version.ref = "commonsNet" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
jimfs = { module = "com.google.jimfs:jimfs", version.ref = "jimfs" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutinesCore" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinxCoroutinesCore" }
logback-android = { module = "com.github.tony19:logback-android", version.ref = "logbackAndroid" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
androidx-navigation-fragment-ktx = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "navigationFragmentKtx" }
androidx-navigation-ui-ktx = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "navigationUiKtx" }
mock-ftp-server = { module = "org.mockftpserver:MockFtpServer", version.ref = "mockftpserver" }
testcontainers = { module = "org.testcontainers:testcontainers", version.ref = "testcontainers" }
mockk-agent = { module = "io.mockk:mockk-agent", version.ref = "mockkVersion" }
mockk-android = { module = "io.mockk:mockk-android", version.ref = "mockkVersion" }
mockwebserver = { module = "com.squareup.okhttp3:mockwebserver", version.ref = "okhttp" }
nio = { module = "com.github.topjohnwu.libsu:nio", version.ref = "libsuVersion" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
prov = { module = "com.madgag.spongycastle:prov", version.ref = "prov" }
simplemagic = { module = "com.j256.simplemagic:simplemagic", version.ref = "simplemagic" }
sshj = { module = "com.hierynomus:sshj", version.ref = "sshj" }
smbj = { module = "com.hierynomus:smbj", version.ref = "smbj" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
jetbrainsKotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
googleKsp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
