services:
  main:
    build:
      context: ..
      dockerfile: ./dev.Dockerfile
      args:
        - USER_NAME=${CONTAINER_USERNAME}
    ports:
      - "6081:6080" # noVNC web interface
      - "5902:5901" # VNC direct connection
      - "5556:5555" # ADB
      - "4724:4723" # Appium
      - "4422:22" # ssh
    environment:
      - VNC_PASSWD=${VNC_PASSWD}
      - TESTCONTAINERS_HOST_OVERRIDE=host.docker.internal # 如果需要Test Container 的话
      - VNC_GEOMETRY=1920x1080
      - VNC_DEPTH=24
    volumes:
      - ..:/workspace/AFS:cached
      - ./data/authorized_keys:${CONTAINER_HOME}/.ssh/authorized_keys
      - /var/run/docker.sock:/var/run/docker.sock # 宿主机 Docker 套接字
      - avd_data:${CONTAINER_HOME}/.android/avd
      - sdk_data:${CONTAINER_HOME}/Android/Sdk
      - a-bashhistory:/commandhistory
      - gradle_data:${CONTAINER_HOME}/.gradle
      - konan_data:${CONTAINER_HOME}/.konan
      - m2_data:${CONTAINER_HOME}/.m2
      - chrome_cache:${CONTAINER_HOME}/.cache/google-chrome
      - chrome_config:${CONTAINER_HOME}/.config/google-chrome
      - google_cache:${CONTAINER_HOME}/.cache/Google
      - google_config:${CONTAINER_HOME}/.config/Google
      - google_local:${CONTAINER_HOME}/.local/share/Google
      - antigravity_config:${CONTAINER_HOME}/.config/Antigravity
      - gemini_data:${CONTAINER_HOME}/.gemini
    shm_size: '2gb' # Allocate more shared memory
    privileged: true # Enable KVM acceleration

volumes:
  avd_data:
  sdk_data:
    name: sdk_data
    external: true
  a-bashhistory:
  gradle_data:
  konan_data:
  m2_data:
  chrome_cache:
  chrome_config:
  google_cache:
  google_config:
  google_local:
  antigravity_config:
  gemini_data:
